export function login(email, password){
  /*
    HERE YOU NEED TO MAKE A CALL TO YOUR API TO VALIDATE THE AUTHENTICATION
    WE FAKE THIS AND ASSUME A SUCCESSFUL RESPONSE FROM THE SERVER
    YOU WILL NEED TO HANDLE THE CASES FOR UNSUCCESS AS WELL AS ERRORS
  */
  return {type: 'LOGIN/SUCCESS', data: {token: 'token', email: email}}
}

export function logout(){
  /*
    HERE WE LOG OUT BY DESTROYING OUR LOCAL REFERENCE TO THE TOKEN. YOU MAY ALSO WANT TO
    INVALIDATE THE TOKEN ON YOUR SERVER FOR ADDED SECURITY.
  */
  return {type: 'LOGOUT/SUCCESS'}
}